//
//  FeedWorker.swift
//  FSCSlutsky
//
//  Created by Павел on 12.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FeedService {
    var authService: AuthService
    var networking: NetworkingProtocol
    var fethcer: DataFetcher
    private var feedResponse: Feeds?
    
    init() {
        self.authService = SceneDelegate.shared().authService
        self.networking = NetworkService(authService: authService)
        self.fethcer = NetworkDataFetcher(networking: networking)
    }
    
    func getFeed(completion: @escaping (Feeds) -> Void) {
        fethcer.getFeed { [weak self] (feed) in
            self?.feedResponse = feed
            guard let feedResponse = self?.feedResponse else { return }
            completion(feedResponse)
        }
    }
}
